# Deployment da app web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-pes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-pes
  template:
    metadata:
      labels:
        app: conv-pes
    spec:
      containers:
      - name: conv-pes
        image: guimap/conversao-peso:latest
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conv-pes
spec:
  selector:
    app: conv-pes
  ports:
  - port: 8081
    targetPort: 80
    type: LoadBalancer
